In [1]:
import pandas as pd

In [3]:
data=pd.read_csv('C:\IDE\data\ErrorEnCoding.csv', header=None, encoding_errors='replace') 
display(data)

<>:1: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
<>:1: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
C:\Users\egork\AppData\Local\Temp\ipykernel_8020\2681311785.py:1: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
  data=pd.read_csv('C:\IDE\data\ErrorEnCoding.csv', header=None, encoding_errors='replace')

            0                           1             2
0   User_943         Accumanst@gmail.com         ������
1   User_908           Advismowr@mail.ru         ������
2   User_962             Anachso@ukr.net      ���������
3   User_973            Antecia@inbox.ru          �����
4   User_902          Balliaryva@ukr.net
..        ...                         ...           ...
95  User_959    UpdatesCurious@yahoo.com         ������
96  User_901          V2artierso@mail.ru    �����������
97  User_970            Vashoterlo@bk.ru        �������
98  User_965         Visuareda@yahoo.com        �������
99  User_921                Aavast@ya.ru         ������

[100 rows x 3 columns]

In [4]:
from chardet.universaldetector import UniversalDetector
detector = UniversalDetector()
with open('C:\IDE\data\ErrorEnCoding.csv', 'rb') as fh:
    for line in fh:
        detector.feed(line)
        if detector.done:
            break
print(detector.close())

<>:3: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
<>:3: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
C:\Users\egork\AppData\Local\Temp\ipykernel_8020\2051585899.py:3: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
  with open('C:\IDE\data\ErrorEnCoding.csv', 'rb') as fh:
C:\Users\egork\AppData\Local\Temp\ipykernel_8020\2051585899.py:1: DeprecationWarning: chardet.universaldetector is deprecated, import UniversalDetector from chardet or chardet.detector instead
  from chardet.universaldetector import UniversalDetector

{'encoding': 'KOI8-R', 'confidence': 0.31946375814590433, 'language': 'ru'}

In [5]:
data=pd.read_csv('C:\IDE\data\ErrorEnCoding.csv', encoding='koi8-r', header=None)
display(data)

<>:1: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
<>:1: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
C:\Users\egork\AppData\Local\Temp\ipykernel_8020\3828315413.py:1: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
  data=pd.read_csv('C:\IDE\data\ErrorEnCoding.csv', encoding='koi8-r', header=None)

            0                           1             2
0   User_943         Accumanst@gmail.com         Ижевск
1   User_908           Advismowr@mail.ru         Ижевск
2   User_962             Anachso@ukr.net      Краснодар
3   User_973            Antecia@inbox.ru          Пермь
4   User_902          Balliaryva@ukr.net
..        ...                         ...           ...
95  User_959    UpdatesCurious@yahoo.com         Тюмень
96  User_901          V2artierso@mail.ru    Арзангелтск
97  User_970            Vashoterlo@bk.ru        Воронеж
98  User_965         Visuareda@yahoo.com        Воронеж
99  User_921                Aavast@ya.ru         Ижевск

[100 rows x 3 columns]