In [1]:
import pandas as pd

In [2]:
grades = pd.read_excel('C:\IDE\data\grades.xlsx')
display(grades.head())

<>:1: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
<>:1: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
C:\Users\egork\AppData\Local\Temp\ipykernel_9004\2563457474.py:1: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
  grades = pd.read_excel('C:\IDE\data\grades.xlsx')

   Student ID Student name  Grade
0           1          Аня      8
1           2         Катя      9
2           3         Маша      7
3           4         Миша      4
4           5         Женя      8

In [3]:
data = pd.read_excel('https://github.com/asaydn/test/raw/master/january.xlsx', skiprows=3)
display(data)

      Location  Oranges  Apples  Bananas  Blueberries  Total
0      Toronto     7651    4422     8580         3679  24332
1  Los Angeles      273    2998     9890         7293  20454
2      Atlanta     3758    6752     4599         4149  19258
3     New York     4019    8796     8486         9188  30489

In [4]:
grades = pd.read_excel('C:\IDE\data\grades.xlsx', sheet_name='ML')
display(grades.head())

<>:1: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
<>:1: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
C:\Users\egork\AppData\Local\Temp\ipykernel_9004\3562939016.py:1: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
  grades = pd.read_excel('C:\IDE\data\grades.xlsx', sheet_name='ML')

   Student ID Student name  Grade
0           1          Аня      7
1           2         Катя      5
2           3         Маша      9
3           4         Миша      8
4           5         Женя      9

In [5]:
grades.to_excel('C:\IDE\data\grades.xlsx')

<>:1: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
<>:1: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
C:\Users\egork\AppData\Local\Temp\ipykernel_9004\1233337203.py:1: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
  grades.to_excel('C:\IDE\data\grades.xlsx')

In [8]:
grades.to_excel('C:\IDE\data\grades.xlsx', sheet_name='Example', index=False)

<>:1: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
<>:1: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
C:\Users\egork\AppData\Local\Temp\ipykernel_9004\1949357202.py:1: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
  grades.to_excel('C:\IDE\data\grades.xlsx', sheet_name='Example', index=False)